project:
  type: book

book:
  title: "Statistics for Excel Users"
  author: "Ronald Mego"
  date: "01/26/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo